### PR TITLE
Fix env util invocation on non-GNU environments.

### LINKED ISSUE #396: Disconnect signal as soon as user is provided during login
It seems wetty sends a disconnect signal when I enter a username to login.

1. yarn global add wetty
2. start wetty server on localhost (with/without nginx)
3. navigate to localhost:3000/wetty
4. type in username and hit enter (tried different names)
5. nothing happens from the web side

Expect response - ask for password, or say bad username, but it appears to disconnect on back end but does not end connection. If I stop the server the web side says transport close.

wetty -c /bin/bash -p 3000
{"base":"/wetty/","label":"Wetty","level":"info","message":"Starting server","port":3000,"timestamp":"2022-04-12T23:40:42.651Z","title":"WeTTY - The Web Terminal Emulator"}
{"connection":"http","label":"Wetty","level":"info","message":"Server started","port":3000,"timestamp":"2022-04-12T23:40:42.663Z"}
{"label":"Wetty","level":"http","message":"GET /wetty 200 8ms","meta":{"req":{"headers":{"accept":"text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8","accept-encoding":"gzip, deflate, br","accept-language":"en-US,en;q=0.5","authorization":"Basic bmdpbng6ZGV3","connection":"upgrade","host":"localhost:38000","sec-fetch-dest":"document","sec-fetch-mode":"navigate","sec-fetch-site":"none","sec-fetch-user":"?1","upgrade-insecure-requests":"1","user-agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:99.0) Gecko/20100101 Firefox/99.0","x-forwarded-for":"127.0.0.1","x-real-ip":"127.0.0.1"},"httpVersion":"1.1","method":"GET","originalUrl":"/wetty","query":{},"url":"/wetty"},"res":{"statusCode":200},"responseTime":8},"timestamp":"2022-04-12T23:41:23.287Z"}
{"label":"Wetty","level":"info","message":"Connection accepted.","timestamp":"2022-04-12T23:41:23.464Z"}
{"label":"Wetty","level":"info","message":"Authentication Type: password","timestamp":"2022-04-12T23:41:23.465Z"}
{"label":"Wetty","level":"http","message":"GET /wetty/favicon.ico 200 20ms","meta":{"req":{"headers":{"accept":"image/avif,image/webp,*/*","accept-encoding":"gzip, deflate, br","accept-language":"en-US,en;q=0.5","authorization":"Basic bmdpbng6ZGV3","connection":"upgrade","host":"localhost:38000","referer":"https://localhost:38000/wetty","sec-fetch-dest":"image","sec-fetch-mode":"no-cors","sec-fetch-site":"same-origin","user-agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:99.0) Gecko/20100101 Firefox/99.0","x-forwarded-for":"127.0.0.1","x-real-ip":"127.0.0.1"},"httpVersion":"1.1","method":"GET","originalUrl":"/wetty/favicon.ico","query":{},"url":"/wetty/favicon.ico"},"res":{"statusCode":200},"responseTime":20},"timestamp":"2022-04-12T23:41:23.475Z"}
{"err":{},"label":"Wetty","level":"info","message":"Disconnect signal sent","timestamp":"2022-04-12T23:41:37.158Z"}

Desktop (please complete the following information):**
 - OS: MacOS Catalina
 - Browser: chrome and firefox *tried both

### PR DESCRIPTION
**Pull request by Warr1024**
If `env --version` invocation crashes, returns unexpected results, or otherwise fails, allow a default fallback version to be used instead of crashing the whole connection, so WeTTY can fall back on "safe" compatible default behavior.

This should fix #396.

### CODE REVIEW

File: src/server/spawn.ts [hunk 1]
```diff
@@ -3,15 +3,15 @@ import isUndefined from 'lodash/isUndefined.js';
 import pty from 'node-pty';
 import { logger as getLogger } from '../shared/logger.js';
 import { xterm } from './shared/xterm.js';
-import { envVersion } from './spawn/env.js';
```
Comment (butlerx) [inline src/server/spawn.ts:6]: Small nitpick can you remove export of `encVersion`

**Review by butlerx — APPROVED** [review]
